/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_2_0;
import java.io.*;
import java.util.*;
import javax.swing.*;

public class AVANZAR extends javax.swing.JFrame {
    private JFrame anterior;
    private int nivel;
    private String nombreJugador; 
    private int puntaje; 
    
    public AVANZAR(JFrame anterior, int nivel, String nombreJugador, int puntaje) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.pack();
        
        this.anterior = anterior;
        this.nivel = nivel;
        this.nombreJugador = nombreJugador;
        this.puntaje = puntaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(109, 84, 34));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("            GANASTE!!!");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 500, -1));

        jButton1.setBackground(new java.awt.Color(209, 167, 122));
        jButton1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGUIENTE NIVEL");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 60));

        salir.setBackground(new java.awt.Color(209, 167, 122));
        salir.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("SALIR");
        salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 180, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(94, 69, 69));
        jLabel2.setText("¿Deseas seguir con el siguiente nivel?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_avanzar.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.nivel == 2){
            NIVEL_2 obj = new NIVEL_2(anterior, nombreJugador, puntaje); 
            obj.setVisible(true);
            this.dispose();
        }else if(this.nivel == 3){
            NIVEL_3 obj = new NIVEL_3(anterior, nombreJugador, puntaje);
            obj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        guardarPuntaje(nombreJugador, puntaje); 
        anterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void guardarPuntaje(String nombre, int puntaje) {
        File archivo = new File("jugadores.txt");
        List<String> lineas = new ArrayList<>();
        boolean jugadorEncontrado = false;

        java.time.LocalDate fecha = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");

        if (archivo.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = br.readLine()) != null) {
                    String[] partes = linea.split(",");
                    if (partes.length >= 2 && partes[0].trim().equalsIgnoreCase(nombre)) {
                        // Reemplaza el puntaje existente por el puntaje total acumulado actual
                        lineas.add(nombre + "," + puntaje + "," + fecha.format(formato));
                        jugadorEncontrado = true;
                    } else {
                        lineas.add(linea);
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        if (!jugadorEncontrado) {
            lineas.add(nombre + "," + puntaje + "," + fecha.format(formato));
        }

        // Sobrescribe el archivo con la info actualizada
        try (PrintWriter pw = new PrintWriter(new FileWriter(archivo, false))) {
            for (String l : lineas) {
                pw.println(l);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
