/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_2_0;
import javax.swing.*;
import java.util.*;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class JUEGO_AUTO extends javax.swing.JFrame {
    private JFrame anterior;
    private String seleccion;
    private int[][] estadoInicial;
    private int[][] estadoMeta;
    private List<BAB> caminoSolucion;  // Lista de pasos de la solución
    private JPanel panelTablero;
    private Timer timer;
    private int pasoActual = 0;
     
    public JUEGO_AUTO(int[][] estadoInicial, int[][] estadoMeta, String seleccion) {
        this.estadoInicial = estadoInicial;
        this.estadoMeta = estadoMeta;
        this.seleccion = seleccion;
        
        initComponents();
        jPanel2.setLayout(new java.awt.GridLayout(3, 3)); 
        mezclarBotones();
        btn9.setVisible(false);
        
        this.setLocationRelativeTo(null);
        this.pack();
        
        this.anterior = anterior;
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                anterior.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new java.awt.GridLayout());

        btn1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btn4.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btn7.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 810, 460));

        jButton19.setBackground(new java.awt.Color(204, 153, 0));
        jButton19.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 0, 0));
        jButton19.setText("INICIAR JUEGO");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 170, 60));

        jButton20.setBackground(new java.awt.Color(204, 153, 0));
        jButton20.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 0, 0));
        jButton20.setText("SALIR");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 170, 60));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_auto.jpg"))); // NOI18N
        fondo1.setOpaque(true);
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (!btn2.isVisible()) {
            btn2.setText(btn1.getText());
            btn2.setVisible(true);
            btn1.setVisible(false);
        } else if (!btn4.isVisible()) {
            btn4.setText(btn1.getText());
            btn4.setVisible(true);
            btn1.setVisible(false);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (!btn1.isVisible()) {
            btn1.setText(btn2.getText());
            btn1.setVisible(true);
            btn2.setVisible(false);
        } else if (!btn3.isVisible()) {
            btn3.setText(btn2.getText());
            btn3.setVisible(true);
            btn2.setVisible(false);
        } else if (!btn5.isVisible()) {
            btn5.setText(btn2.getText());
            btn5.setVisible(true);
            btn2.setVisible(false);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (!btn2.isVisible()) {
            btn2.setText(btn3.getText());
            btn2.setVisible(true);
            btn3.setVisible(false);
        } else if (!btn6.isVisible()) {
            btn6.setText(btn3.getText());
            btn6.setVisible(true);
            btn3.setVisible(false);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (!btn1.isVisible()) {
            btn1.setText(btn4.getText());
            btn1.setVisible(true);
            btn4.setVisible(false);
        } else if (!btn5.isVisible()) {
            btn5.setText(btn4.getText());
            btn5.setVisible(true);
            btn4.setVisible(false);
        } else if (!btn7.isVisible()) {
            btn7.setText(btn4.getText());
            btn7.setVisible(true);
            btn4.setVisible(false);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (!btn2.isVisible()) {
            btn2.setText(btn5.getText());
            btn2.setVisible(true);
            btn5.setVisible(false);
        } else if (!btn4.isVisible()) {
            btn4.setText(btn5.getText());
            btn4.setVisible(true);
            btn5.setVisible(false);
        } else if (!btn6.isVisible()) {
            btn6.setText(btn5.getText());
            btn6.setVisible(true);
            btn5.setVisible(false);
        } else if (!btn8.isVisible()) {
            btn8.setText(btn5.getText());
            btn8.setVisible(true);
            btn5.setVisible(false);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (!btn3.isVisible()) {
            btn3.setText(btn6.getText());
            btn3.setVisible(true);
            btn6.setVisible(false);
        } else if (!btn5.isVisible()) {
            btn5.setText(btn6.getText());
            btn5.setVisible(true);
            btn6.setVisible(false);
        } else if (!btn9.isVisible()) {
            btn9.setText(btn6.getText());
            btn9.setVisible(true);
            btn6.setVisible(false);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (!btn4.isVisible()) {
            btn4.setText(btn7.getText());
            btn4.setVisible(true);
            btn7.setVisible(false);
        } else if (!btn8.isVisible()) {
            btn8.setText(btn7.getText());
            btn8.setVisible(true);
            btn7.setVisible(false);
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (!btn5.isVisible()) {
            btn5.setText(btn8.getText());
            btn5.setVisible(true);
            btn8.setVisible(false);
        } else if (!btn7.isVisible()) {
            btn7.setText(btn8.getText());
            btn7.setVisible(true);
            btn8.setVisible(false);
        } else if (!btn9.isVisible()) {
            btn9.setText(btn8.getText());
            btn9.setVisible(true);
            btn8.setVisible(false);
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (!btn6.isVisible()) {
            btn6.setText(btn9.getText());
            btn6.setVisible(true);
            btn9.setVisible(false);
        } else if (!btn8.isVisible()) {
            btn8.setText(btn9.getText());
            btn8.setVisible(true);
            btn9.setVisible(false);
        }
    }//GEN-LAST:event_btn9ActionPerformed
    private void mezclarBotones(){
        String[] numeros = {"1", "2", "3", "4", "5", "6", "7", "8"};
        java.util.List<String> lista = java.util.Arrays.asList(numeros); // Se conviente el vector a una lista para poder usar el shuffle
        java.util.Collections.shuffle(lista); // Se mezclan los elementos de forma aleatoria 

        javax.swing.JButton[] botones = {btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8}; // Arreglo de botones 

        for(int i = 0; i < botones.length; i++){
            botones[i].setText(lista.get(i)); // Se le asigna un numero aleatorio al boton
            botones[i].setVisible(true); // Lo hace visible
        }
    }
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        int[][] estadoInicial = generarEstadoInicialResoluble();
        int[][] estadoFinal;

        switch (seleccion) {
            case "Horizontal":
            estadoFinal = new int[][] {
                {1, 2, 3},
                {4, 5, 6},
                {7, 8, 0}
            };
            break;
            case "Vertical":
            estadoFinal = new int[][] {
                {1, 4, 7},
                {2, 5, 8},
                {3, 6, 0}
            };
            break;
            case "CARACOL":
            estadoFinal = new int[][] {
                {5, 6, 7},
                {4, 1, 8},
                {3, 2, 0}
            };
            break;
            case "Imposible":
            estadoFinal = new int[][] {
                {1, 2, 3},
                {4, 5, 6},
                {8, 7, 0}
            };
            break;
            default:
            estadoFinal = new int[][] {
                {1, 2, 3},
                {4, 5, 6},
                {7, 8, 0}
            };
            break;
        }

        BAB bab = new BAB();
        List<BAB.PuzzleNode> solucion = bab.resolver(estadoInicial, estadoFinal);

        if (solucion == null || solucion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay solución.");
            return;
        }

        final int[] paso = {0};
        Timer timer = new Timer(700, null);

        timer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (paso[0] < solucion.size()) {
                    int[][] tablero = solucion.get(paso[0]).estado;
                    actualizarBotones(tablero);
                    paso[0]++;
                } else {
                    timer.stop();
                    JOptionPane.showMessageDialog(null, "¡Super, felicidades, lo lograste :)");
                }
            }
        });

        timer.start();
        }
        private void actualizarBotones(int[][] estado) {
            JButton[] botones = {btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9};
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    int valor = estado[i][j];
                    int index = i * 3 + j;
                    if (valor == 0) {
                        botones[index].setVisible(false);
                    } else {
                        botones[index].setText(String.valueOf(valor));
                        botones[index].setVisible(true);
                    }
                }
            }
        }
        private int[][] generarEstadoInicialResoluble() {
            List<Integer> numeros = new ArrayList<>();
            for (int i = 0; i <= 8; i++) {
                numeros.add(i);
            }

            int[][] estado = new int[3][3];
            do {
                Collections.shuffle(numeros);
                for (int i = 0; i < 9; i++) {
                    estado[i / 3][i % 3] = numeros.get(i);
                }
            } while (!esSoluble(estado));
            return estado;
        }

        private boolean esSoluble(int[][] puzzle) {
            int[] plano = new int[9];
            int index = 0;
            for (int[] fila : puzzle) {
                for (int n : fila) {
                    plano[index++] = n;
                }
            }

            int inversiones = 0;
            for (int i = 0; i < 9; i++) {
                for (int j = i + 1; j < 9; j++) {
                    if (plano[i] != 0 && plano[j] != 0 && plano[i] > plano[j]) {
                        inversiones++;
                    }
                }
            }

            return inversiones % 2 == 0;
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        INICIO pantallaInicio = new INICIO();
        pantallaInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel fondo1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
