
package com.mycompany.proyecto_final_2_0;
import javax.swing.*;
import java.net.URL;

public class NIVEL_2 extends javax.swing.JFrame {
    private JFrame anterior;
    private JButton[] botones;
    private int blanco; 
    
    public NIVEL_2(JFrame anterior) {
        initComponents();
        
        botones = new JButton[]{btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9};
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 450));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3)); // fila, columnas
        mezclarBotones();
        
        this.setLocationRelativeTo(null);
        this.pack();
        
        this.anterior = anterior;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        btn1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        btn1.setPreferredSize(new java.awt.Dimension(147, 147));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btn4.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btn7.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/7.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 450, 450));

        jButton10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton10.setText("Reiniciar ");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 240, 120, 50));

        jButton11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton11.setText("Salir");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_nivel2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (!btn2.isVisible()) {
            btn2.setIcon(btn1.getIcon());
            btn2.setVisible(true);
            btn1.setVisible(false);
        } else if (!btn4.isVisible()) {
            btn4.setIcon(btn1.getIcon());
            btn4.setVisible(true);
            btn1.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (!btn1.isVisible()) {
            btn1.setIcon(btn2.getIcon());
            btn1.setVisible(true);
            btn2.setVisible(false);
        } else if (!btn3.isVisible()) {
            btn3.setIcon(btn2.getIcon());
            btn3.setVisible(true);
            btn2.setVisible(false);
        } else if (!btn5.isVisible()) {
            btn5.setIcon(btn2.getIcon());
            btn5.setVisible(true);
            btn2.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (!btn2.isVisible()) {
            btn2.setIcon(btn3.getIcon());
            btn2.setVisible(true);
            btn3.setVisible(false);
        } else if (!btn6.isVisible()) {
            btn6.setIcon(btn3.getIcon());
            btn6.setVisible(true);
            btn3.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (!btn1.isVisible()) {
            btn1.setIcon(btn4.getIcon());
            btn1.setVisible(true);
            btn4.setVisible(false);
        } else if (!btn5.isVisible()) {
            btn5.setIcon(btn4.getIcon());
            btn5.setVisible(true);
            btn4.setVisible(false);
        } else if (!btn7.isVisible()) {
            btn7.setIcon(btn4.getIcon());
            btn7.setVisible(true);
            btn4.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (!btn2.isVisible()) {
            btn2.setIcon(btn5.getIcon());
            btn2.setVisible(true);
            btn5.setVisible(false);
        } else if (!btn4.isVisible()) {
            btn4.setIcon(btn5.getIcon());
            btn4.setVisible(true);
            btn5.setVisible(false);
        } else if (!btn6.isVisible()) {
            btn6.setIcon(btn5.getIcon());
            btn6.setVisible(true);
            btn5.setVisible(false);
        } else if (!btn8.isVisible()) {
            btn8.setIcon(btn5.getIcon());
            btn8.setVisible(true);
            btn5.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (!btn3.isVisible()) {
            btn3.setIcon(btn6.getIcon());
            btn3.setVisible(true);
            btn6.setVisible(false);
        } else if (!btn5.isVisible()) {
            btn5.setIcon(btn6.getIcon());
            btn5.setVisible(true);
            btn6.setVisible(false);
        } else if (!btn9.isVisible()) {
            btn9.setIcon(btn6.getIcon());
            btn9.setVisible(true);
            btn6.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (!btn4.isVisible()) {
            btn4.setIcon(btn7.getIcon());
            btn4.setVisible(true);
            btn7.setVisible(false);
        } else if (!btn8.isVisible()) {
            btn8.setIcon(btn7.getIcon());
            btn8.setVisible(true);
            btn7.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (!btn5.isVisible()) {
            btn5.setIcon(btn8.getIcon());
            btn5.setVisible(true);
            btn8.setVisible(false);
        } else if (!btn7.isVisible()) {
            btn7.setIcon(btn8.getIcon());
            btn7.setVisible(true);
            btn8.setVisible(false);
        } else if (!btn9.isVisible()) {
            btn9.setIcon(btn8.getIcon());
            btn9.setVisible(true);
            btn8.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (!btn6.isVisible()) {
            btn6.setIcon(btn9.getIcon());
            btn6.setVisible(true);
            btn9.setVisible(false);
        } else if (!btn8.isVisible()) {
            btn8.setIcon(btn9.getIcon());
            btn8.setVisible(true);
            btn9.setVisible(false);
        }
        verificarVictoria();
    }//GEN-LAST:event_btn9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        mezclarBotones();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
        anterior.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed
    
     private void mezclarBotones(){
        String[] numeros = {"/1.png", "/2.png", "/3.png", "/4.png", "/5.png", "/6.png", "/7.png", "/8.png", "/0.png"};
        for (int i = 0; i < botones.length; i++) {
            URL ruta = getClass().getResource(numeros[i]);
            botones[i].setIcon(new ImageIcon(ruta));
            botones[i].setVisible(true);
        }
        
        botones[8].setVisible(false); // espacio vacío
        blanco = 8;
        
        for (int i = 0; i < 30; i++) {
            moverEspacioAleatoriamente();
        }
    }
    private void moverEspacioAleatoriamente() {
        int[][] vecinos = {
            {1, 3},        // 0
            {0, 2, 4},     // 1
            {1, 5},        // 2
            {0, 4, 6},     // 3
            {1, 3, 5, 7},  // 4
            {2, 4, 8},     // 5
            {3, 7},        // 6
            {4, 6, 8},     // 7
            {5, 7}         // 8
        };

        int[] opciones = vecinos[blanco];
        int destino = opciones[(int)(Math.random() * opciones.length)];

        // Intercambia íconos
        Icon temp = botones[destino].getIcon();
        botones[destino].setIcon(botones[blanco].getIcon());
        botones[blanco].setIcon(temp);

        botones[destino].setVisible(false);
        botones[blanco].setVisible(true);

        blanco = destino;
    }
    
    private void verificarVictoria() {
        String[] ordenCorrecto = {
            "/1.png", "/2.png", "/3.png",
            "/4.png", "/5.png", "/6.png",
            "/7.png", "/8.png"
        };

        JButton[] botones = { btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8 };

        for (int i = 0; i < botones.length; i++) {
            Icon icon = botones[i].getIcon();
            URL imagenCorrecta = getClass().getResource(ordenCorrecto[i]);

            if (icon == null || imagenCorrecta == null) return;

            Icon iconoCorrecto = new ImageIcon(imagenCorrecta);

            if (!icon.toString().equals(iconoCorrecto.toString())) {
                return; // No ha ganado todavía
            }
        }

        // Si llegó hasta aquí, ¡ganó!
        AVANZAR obj = new AVANZAR(anterior, 3);
        obj.setVisible(true);
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
